-- BJN · CHG-021 · 2026-07-21
-- 리뷰 이미지 전용 연결 테이블 신설
-- REVIEW_IMAGE는 리뷰 소유자(담당자3 HSK)가 소유하며, REVIEW → FILES를 연결한다.

CREATE TABLE IF NOT EXISTS REVIEW_IMAGE
(
    RVW_IMG_SN      BIGINT      NOT NULL AUTO_INCREMENT COMMENT '리뷰이미지일련번호',
    RVW_SN          BIGINT      NOT NULL COMMENT '리뷰일련번호',
    FL_SN           BIGINT      NOT NULL COMMENT '파일일련번호',
    RVW_IMG_SORT_NO INT         NOT NULL DEFAULT 0 COMMENT '정렬순서',
    RVW_IMG_REG_DT  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    PRIMARY KEY (RVW_IMG_SN),
    KEY IDX_REVIEW_IMAGE_RVW_SN (RVW_SN),
    CONSTRAINT FK_REVIEW_IMAGE_REVIEW
        FOREIGN KEY (RVW_SN)
        REFERENCES REVIEW (RVW_SN)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_REVIEW_IMAGE_FILES
        FOREIGN KEY (FL_SN)
        REFERENCES FILES (FL_SN)
        ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = '리뷰이미지';

-- 적용 결과 확인: REVIEW_IMAGE 테이블이 조회되면 정상
SELECT TABLE_NAME, TABLE_COMMENT, CREATE_TIME
  FROM INFORMATION_SCHEMA.TABLES
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'REVIEW_IMAGE';
