USE NCTDB;

-- =========================================================
-- 상품 관심 테이블 추가
-- =========================================================

CREATE TABLE IF NOT EXISTS PRODUCT_FAVORITE
(
    PRD_FAV_SN
        BIGINT NOT NULL AUTO_INCREMENT
        COMMENT '상품관심일련번호',

    PRD_SN
        BIGINT NOT NULL
        COMMENT '상품일련번호',

    USR_SN
        BIGINT NOT NULL
        COMMENT '회원일련번호',

    PRD_FAV_USE_YN
        CHAR(1) NOT NULL DEFAULT 'Y'
        COMMENT '상품관심사용여부',

    PRD_FAV_REG_DT
        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        COMMENT '등록일시',

    PRD_FAV_UPDT_DT
        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
        COMMENT '갱신일시',

    PRD_FAV_REG_ID
        VARCHAR(50) NOT NULL DEFAULT 'SYSTEM'
        COMMENT '등록자ID',

    PRD_FAV_UPDT_ID
        VARCHAR(50) NOT NULL DEFAULT 'SYSTEM'
        COMMENT '갱신자ID',

    PRIMARY KEY (PRD_FAV_SN),

    UNIQUE KEY UK_PRODUCT_FAVORITE_USER_PRODUCT (
        USR_SN,
        PRD_SN
    ),

    KEY IDX_PRODUCT_FAVORITE_PRODUCT (
        PRD_SN,
        PRD_FAV_USE_YN
    ),

    KEY IDX_PRODUCT_FAVORITE_USER (
        USR_SN,
        PRD_FAV_USE_YN,
        PRD_FAV_REG_DT
    ),

    CONSTRAINT CK_PRODUCT_FAVORITE_USE_YN
        CHECK (PRD_FAV_USE_YN IN ('Y', 'N')),

    CONSTRAINT FK_PRODUCT_FAVORITE_PRODUCT
        FOREIGN KEY (PRD_SN)
        REFERENCES PRODUCT (PRD_SN)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT,

    CONSTRAINT FK_PRODUCT_FAVORITE_USER
        FOREIGN KEY (USR_SN)
        REFERENCES USERS (USR_SN)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = '상품 관심';

-- 기존 개발 DB에 PRODUCT_FAVORITE가 먼저 만들어져 있고 사용여부 컬럼만 없는 경우 보정한다.
SET @column_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'PRODUCT_FAVORITE'
       AND COLUMN_NAME = 'PRD_FAV_USE_YN'
);
SET @sql := IF(
    @column_exists = 0,
    'ALTER TABLE PRODUCT_FAVORITE ADD COLUMN PRD_FAV_USE_YN CHAR(1) NOT NULL DEFAULT ''Y'' COMMENT ''상품관심사용여부'' AFTER USR_SN',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @index_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.STATISTICS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'PRODUCT_FAVORITE'
       AND INDEX_NAME = 'IDX_PRODUCT_FAVORITE_PRODUCT'
);
SET @sql := IF(
    @index_exists = 0,
    'CREATE INDEX IDX_PRODUCT_FAVORITE_PRODUCT ON PRODUCT_FAVORITE (PRD_SN, PRD_FAV_USE_YN)',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @index_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.STATISTICS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'PRODUCT_FAVORITE'
       AND INDEX_NAME = 'IDX_PRODUCT_FAVORITE_USER'
);
SET @sql := IF(
    @index_exists = 0,
    'CREATE INDEX IDX_PRODUCT_FAVORITE_USER ON PRODUCT_FAVORITE (USR_SN, PRD_FAV_USE_YN, PRD_FAV_REG_DT)',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @constraint_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'PRODUCT_FAVORITE'
       AND CONSTRAINT_NAME = 'CK_PRODUCT_FAVORITE_USE_YN'
);
SET @sql := IF(
    @constraint_exists = 0,
    'ALTER TABLE PRODUCT_FAVORITE ADD CONSTRAINT CK_PRODUCT_FAVORITE_USE_YN CHECK (PRD_FAV_USE_YN IN (''Y'', ''N''))',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
