-- 2026-08-06 | QUOTE 예상 소요시간 컬럼 추가 + 견적 작업사진 테이블 신설
-- 담당자3 황성경 (F-SVC-005/006 payload 누락 버그 수정)
USE NCTDB;

ALTER TABLE QUOTE
    ADD COLUMN QUT_ESTM_DRT VARCHAR(100) NULL COMMENT '예상 소요시간' AFTER QUT_CN;

CREATE TABLE IF NOT EXISTS QUOTE_PHOTO (
    QUT_PHT_SN  BIGINT   NOT NULL AUTO_INCREMENT     COMMENT 'PK',
    QUT_SN      BIGINT   NOT NULL                    COMMENT '견적번호 (FK → QUOTE.QUT_SN)',
    FL_SN       BIGINT   NOT NULL                    COMMENT '파일번호 (FK → FILES.FL_SN)',
    SORT_NO     INT      NOT NULL DEFAULT 0           COMMENT '정렬순서 (0 = 대표사진)',
    REG_DT      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (QUT_PHT_SN),
    CONSTRAINT FK_QUOTE_PHOTO_QUOTE FOREIGN KEY (QUT_SN) REFERENCES QUOTE (QUT_SN),
    CONSTRAINT FK_QUOTE_PHOTO_FILE  FOREIGN KEY (FL_SN)  REFERENCES FILES (FL_SN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='견적 작업사진';
