-- F-OPS-009 관리자 정산 보류·해제 이력과 영구 멱등키를 저장한다.
-- 공유 DB에 자동 적용하지 않으며, 정본 승인 후 1회 실행한다.
CREATE TABLE IF NOT EXISTS SETTLEMENT_ADMIN_ACTION
(
    STLM_ADM_ACT_SN       BIGINT       NOT NULL AUTO_INCREMENT COMMENT '관리자정산처리일련번호',
    STLM_SN               BIGINT       NOT NULL COMMENT '정산일련번호',
    STLM_ADM_ACT_TYPE     VARCHAR(20)  NOT NULL COMMENT '처리유형(HOLD/RELEASE)',
    STLM_PREV_STATUS_CD   VARCHAR(30)  NOT NULL COMMENT '처리전정산상태코드',
    STLM_NEXT_STATUS_CD   VARCHAR(30)  NOT NULL COMMENT '처리후정산상태코드',
    STLM_ADM_ACT_RSN_CN   VARCHAR(1000) NOT NULL COMMENT '관리자처리사유',
    STLM_ADM_REQ_ID       VARCHAR(100) NOT NULL COMMENT '관리자처리요청멱등키',
    STLM_PROC_USR_SN      BIGINT       NOT NULL COMMENT '처리관리자회원일련번호',
    STLM_ADM_ACT_REG_DT   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '처리일시',
    PRIMARY KEY (STLM_ADM_ACT_SN),
    UNIQUE KEY UK_SETTLEMENT_ADMIN_REQUEST (STLM_ADM_REQ_ID),
    KEY IDX_SETTLEMENT_ADMIN_ACTION (STLM_SN, STLM_ADM_ACT_SN),
    CONSTRAINT FK_STLM_ADMIN_ACTION_SETTLEMENT FOREIGN KEY (STLM_SN)
        REFERENCES SETTLEMENT (STLM_SN) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_STLM_ADMIN_ACTION_PREV_STATUS FOREIGN KEY (STLM_PREV_STATUS_CD)
        REFERENCES CMM_CODE (CMM_CD) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_STLM_ADMIN_ACTION_NEXT_STATUS FOREIGN KEY (STLM_NEXT_STATUS_CD)
        REFERENCES CMM_CODE (CMM_CD) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_STLM_ADMIN_ACTION_PROCESSOR FOREIGN KEY (STLM_PROC_USR_SN)
        REFERENCES USERS (USR_SN) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci
  COMMENT = '관리자 정산 처리 이력';

-- 적용 검증
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'SETTLEMENT_ADMIN_ACTION'
 ORDER BY ORDINAL_POSITION;

SELECT INDEX_NAME, NON_UNIQUE, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS INDEX_COLUMNS
  FROM INFORMATION_SCHEMA.STATISTICS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'SETTLEMENT_ADMIN_ACTION'
 GROUP BY INDEX_NAME, NON_UNIQUE;
