-- 서비스 견적 선택으로 생성되는 TRADE가 원본 서비스 요청·견적을 추적하도록 한다.
-- 서비스 거래 생성 계약이 확정되기 전에는 두 컬럼을 nullable로 유지해 기존 물건 거래에 영향을 주지 않는다.
ALTER TABLE TRADE
    ADD COLUMN SVC_REQ_SN BIGINT NULL COMMENT '서비스요청일련번호(FK→SERVICE_REQUEST)' AFTER BID_SN,
    ADD COLUMN QUT_SN BIGINT NULL COMMENT '선택견적일련번호(FK→QUOTE)' AFTER SVC_REQ_SN,
    ADD KEY IDX_TRADE_SVC_REQ (SVC_REQ_SN),
    ADD UNIQUE KEY UK_TRADE_QUOTE (QUT_SN),
    ADD CONSTRAINT FK_TRADE_SVC_REQ
        FOREIGN KEY (SVC_REQ_SN)
        REFERENCES SERVICE_REQUEST (SVC_REQ_SN),
    ADD CONSTRAINT FK_TRADE_QUOTE
        FOREIGN KEY (QUT_SN)
        REFERENCES QUOTE (QUT_SN);
