-- F-OPS-002/019 AccountSanctionPort의 제한·해제 명령 멱등키를 보존한다.
-- 공유 DB에 자동 적용하지 않으며, 정본 승인 후 1회 실행한다.
ALTER TABLE SANCTION
    ADD COLUMN SNC_REQ_ID VARCHAR(100) NULL COMMENT '계정 제한 요청 멱등키' AFTER SNC_END_DT,
    ADD COLUMN SNC_REL_REQ_ID VARCHAR(100) NULL COMMENT '계정 제한 해제 요청 멱등키' AFTER SNC_REQ_ID,
    ADD UNIQUE KEY UK_SANCTION_REQ (SNC_REQ_ID),
    ADD UNIQUE KEY UK_SANCTION_RELEASE_REQ (SNC_REL_REQ_ID),
    ADD KEY IDX_SANCTION_ACCOUNT_ACTIVE (USR_SN, SNC_TYPE_CD, SNC_END_DT, SNC_START_DT);

-- 적용 검증
SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'SANCTION'
   AND COLUMN_NAME IN ('SNC_REQ_ID', 'SNC_REL_REQ_ID');

SELECT INDEX_NAME, NON_UNIQUE, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS INDEX_COLUMNS
  FROM INFORMATION_SCHEMA.STATISTICS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'SANCTION'
   AND INDEX_NAME IN ('UK_SANCTION_REQ', 'UK_SANCTION_RELEASE_REQ', 'IDX_SANCTION_ACCOUNT_ACTIVE')
 GROUP BY INDEX_NAME, NON_UNIQUE;

-- 활성 계정 정지 중복 데이터가 없어야 한다.
SELECT USR_SN, COUNT(*) AS ACTIVE_SUSPENSION_COUNT
 FROM SANCTION
 WHERE SNC_TYPE_CD = 'SNCC0003'
   AND SNC_START_DT <= CURRENT_TIMESTAMP
   AND (SNC_END_DT IS NULL OR SNC_END_DT > CURRENT_TIMESTAMP)
 GROUP BY USR_SN
HAVING COUNT(*) > 1;
