-- 회원 다중 배송지와 경매 입찰 시 선택 배송지를 보존한다.
CREATE TABLE USER_DELIVERY_ADDRESS (
    USR_DLVR_ADDR_SN BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원배송지일련번호',
    USR_SN BIGINT NOT NULL COMMENT '회원일련번호',
    USR_DLVR_ADDR_NM VARCHAR(50) NOT NULL COMMENT '배송지명',
    USR_DLVR_ZIP_ENC TEXT NOT NULL COMMENT '우편번호 AES-256-GCM 암호문',
    USR_DLVR_ADDR_ENC TEXT NOT NULL COMMENT '기본주소 AES-256-GCM 암호문',
    USR_DLVR_DADDR_ENC TEXT NULL COMMENT '상세주소 AES-256-GCM 암호문',
    USR_DLVR_DFLT_YN CHAR(1) NOT NULL DEFAULT 'N' COMMENT '기본배송지여부',
    USR_DLVR_USE_YN CHAR(1) NOT NULL DEFAULT 'Y' COMMENT '사용여부',
    USR_DLVR_REG_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일시',
    USR_DLVR_UPDT_DT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일시',
    USR_DLVR_REG_ID VARCHAR(100) NOT NULL COMMENT '등록자ID',
    USR_DLVR_UPDT_ID VARCHAR(100) NOT NULL COMMENT '수정자ID',
    PRIMARY KEY (USR_DLVR_ADDR_SN),
    KEY IDX_USER_DELIVERY_ADDRESS_USER (USR_SN, USR_DLVR_USE_YN, USR_DLVR_DFLT_YN),
    CONSTRAINT FK_USER_DELIVERY_ADDRESS_USER
        FOREIGN KEY (USR_SN) REFERENCES USERS (USR_SN)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT CK_USER_DELIVERY_ADDRESS_DEFAULT
        CHECK (USR_DLVR_DFLT_YN IN ('Y', 'N')),
    CONSTRAINT CK_USER_DELIVERY_ADDRESS_USE
        CHECK (USR_DLVR_USE_YN IN ('Y', 'N'))
) COMMENT='회원 다중 배송지';

-- 기존 USERS 단일 주소는 암호문을 그대로 복사해 기본 배송지로 이관한다.
INSERT INTO USER_DELIVERY_ADDRESS (
    USR_SN,
    USR_DLVR_ADDR_NM,
    USR_DLVR_ZIP_ENC,
    USR_DLVR_ADDR_ENC,
    USR_DLVR_DADDR_ENC,
    USR_DLVR_DFLT_YN,
    USR_DLVR_USE_YN,
    USR_DLVR_REG_ID,
    USR_DLVR_UPDT_ID
)
SELECT
    u.USR_SN,
    '기본 배송지',
    u.USR_ZIP_ENC,
    u.USR_ADDR_ENC,
    u.USR_DADDR_ENC,
    'Y',
    'Y',
    'SYSTEM',
    'SYSTEM'
FROM USERS u
WHERE u.USR_ZIP_ENC IS NOT NULL
  AND u.USR_ADDR_ENC IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM USER_DELIVERY_ADDRESS address
      WHERE address.USR_SN = u.USR_SN
        AND address.USR_DLVR_USE_YN = 'Y'
  );

ALTER TABLE BID
    ADD COLUMN BID_DLVR_ADDR_SN BIGINT NULL COMMENT '입찰자가 선택한 회원배송지일련번호' AFTER BID_TRD_METHOD_CD;

-- 배포 전에 생성된 배송 입찰은 이관된 기본 배송지를 연결한다.
UPDATE BID bid
JOIN USER_DELIVERY_ADDRESS address
  ON address.USR_SN = bid.USR_SN
 AND address.USR_DLVR_USE_YN = 'Y'
 AND address.USR_DLVR_DFLT_YN = 'Y'
SET bid.BID_DLVR_ADDR_SN = address.USR_DLVR_ADDR_SN
WHERE bid.BID_STATUS_CD = 'BIDC0001'
  AND bid.BID_TRD_METHOD_CD = 'TRDC0009'
  AND bid.BID_DLVR_ADDR_SN IS NULL;

ALTER TABLE BID
    ADD KEY IDX_BID_DELIVERY_ADDRESS (BID_DLVR_ADDR_SN),
    ADD CONSTRAINT FK_BID_DELIVERY_ADDRESS
        FOREIGN KEY (BID_DLVR_ADDR_SN)
        REFERENCES USER_DELIVERY_ADDRESS (USR_DLVR_ADDR_SN)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
