USE NCTDB;

-- F-OPS-013: 민감정보 자동 탐지 신고를 RISK_EVENT와 1:1로 연결한다.
-- 기존·수동 신고는 RSK_EVT_SN이 NULL이며, SYSTEM 자동 신고만 신고자 회원번호를 비워 둔다.

SET @column_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND COLUMN_NAME = 'RSK_EVT_SN'
);
SET @sql := IF(
    @column_exists = 0,
    'ALTER TABLE ABUSE_REPORT ADD COLUMN RSK_EVT_SN BIGINT NULL COMMENT ''리스크이벤트일련번호'' AFTER ABR_SN',
    'ALTER TABLE ABUSE_REPORT MODIFY COLUMN RSK_EVT_SN BIGINT NULL COMMENT ''리스크이벤트일련번호'''
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @column_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND COLUMN_NAME = 'ABR_PROC_RSN_CN'
);
SET @sql := IF(
    @column_exists = 0,
    'ALTER TABLE ABUSE_REPORT ADD COLUMN ABR_PROC_RSN_CN VARCHAR(4000) NULL COMMENT ''처리사유내용'' AFTER ABR_CN',
    'ALTER TABLE ABUSE_REPORT MODIFY COLUMN ABR_PROC_RSN_CN VARCHAR(4000) NULL COMMENT ''처리사유내용'''
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @reporter_nullable := (
    SELECT IS_NULLABLE
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND COLUMN_NAME = 'RPRT_USR_SN'
);
SET @sql := IF(
    @reporter_nullable = 'NO',
    'ALTER TABLE ABUSE_REPORT MODIFY COLUMN RPRT_USR_SN BIGINT NULL COMMENT ''신고자회원일련번호(SYSTEM 자동 신고는 NULL)''',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @unique_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.STATISTICS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND INDEX_NAME = 'UK_ABUSE_REPORT_RISK_EVENT'
);
SET @sql := IF(
    @unique_exists = 0,
    'ALTER TABLE ABUSE_REPORT ADD CONSTRAINT UK_ABUSE_REPORT_RISK_EVENT UNIQUE (RSK_EVT_SN)',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @fk_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND CONSTRAINT_NAME = 'FK_ABUSE_REPORT_RISK_EVENT'
       AND CONSTRAINT_TYPE = 'FOREIGN KEY'
);
SET @sql := IF(
    @fk_exists = 0,
    'ALTER TABLE ABUSE_REPORT ADD CONSTRAINT FK_ABUSE_REPORT_RISK_EVENT FOREIGN KEY (RSK_EVT_SN) REFERENCES RISK_EVENT (RSK_EVT_SN) ON DELETE RESTRICT ON UPDATE RESTRICT',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @check_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'ABUSE_REPORT'
       AND CONSTRAINT_NAME = 'CK_ABUSE_REPORT_REPORTER_SOURCE'
       AND CONSTRAINT_TYPE = 'CHECK'
);
SET @sql := IF(
    @check_exists = 0,
    'ALTER TABLE ABUSE_REPORT ADD CONSTRAINT CK_ABUSE_REPORT_REPORTER_SOURCE CHECK ((RSK_EVT_SN IS NULL AND RPRT_USR_SN IS NOT NULL) OR (RSK_EVT_SN IS NOT NULL AND RPRT_USR_SN IS NULL AND ABR_REG_ID = ''SYSTEM''))',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_COMMENT
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'ABUSE_REPORT'
   AND COLUMN_NAME IN ('RSK_EVT_SN', 'RPRT_USR_SN', 'ABR_PROC_RSN_CN')
 ORDER BY ORDINAL_POSITION;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'ABUSE_REPORT'
   AND CONSTRAINT_NAME IN (
       'UK_ABUSE_REPORT_RISK_EVENT',
       'FK_ABUSE_REPORT_RISK_EVENT',
       'CK_ABUSE_REPORT_REPORTER_SOURCE'
   )
 ORDER BY CONSTRAINT_NAME;
