USE NCTDB;

-- F-AUC-008: 반려 시 취소 요청 전 경매 상태로 복귀하기 위한 상태 스냅샷
-- 기존 요청의 이전 상태는 추측할 수 없으므로 데이터가 없는 상태에서 적용한다.
SET @column_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.COLUMNS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'AUCTION_CANCEL_REQUEST'
       AND COLUMN_NAME = 'PREV_AUC_STATUS_CD'
);

SET @sql := IF(
    @column_exists = 0,
    'ALTER TABLE AUCTION_CANCEL_REQUEST ADD COLUMN PREV_AUC_STATUS_CD VARCHAR(30) NOT NULL COMMENT ''취소 요청 전 경매 상태코드'' AFTER AUC_SN',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @constraint_exists := (
    SELECT COUNT(*)
      FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
     WHERE TABLE_SCHEMA = DATABASE()
       AND TABLE_NAME = 'AUCTION_CANCEL_REQUEST'
       AND CONSTRAINT_NAME = 'CK_AUC_CNL_REQ_PREV_STATUS'
);

SET @sql := IF(
    @constraint_exists = 0,
    'ALTER TABLE AUCTION_CANCEL_REQUEST ADD CONSTRAINT CK_AUC_CNL_REQ_PREV_STATUS CHECK (PREV_AUC_STATUS_CD IN (''AUCC0002'', ''AUCC0003''))',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE
  FROM INFORMATION_SCHEMA.COLUMNS
 WHERE TABLE_SCHEMA = DATABASE()
   AND TABLE_NAME = 'AUCTION_CANCEL_REQUEST'
   AND COLUMN_NAME = 'PREV_AUC_STATUS_CD';
