-- 혼합 상품(TRDC0020)의 낙찰 뒤 실제 거래방식을 보존한다.
-- 기존 단일 방식 거래는 상품 등록 방식을 그대로 이관한다.
ALTER TABLE TRADE
    ADD COLUMN TRD_METHOD_CD VARCHAR(30) NULL COMMENT '확정 거래방식공통코드(TRDG03)' AFTER TRD_STATUS_CD;

UPDATE TRADE t
JOIN PRODUCT p ON p.PRD_SN = t.PRD_SN
SET t.TRD_METHOD_CD = p.PRD_TRD_METHOD_CD
WHERE t.TRD_TYPE_CD = 'TRDC0001'
  AND p.PRD_TRD_METHOD_CD IN ('TRDC0009', 'TRDC0010')
  AND t.TRD_METHOD_CD IS NULL;

ALTER TABLE TRADE
    ADD KEY IDX_TRADE_METHOD (TRD_METHOD_CD),
    ADD CONSTRAINT FK_TRADE_TRD_METHOD_CD
        FOREIGN KEY (TRD_METHOD_CD)
        REFERENCES CMM_CODE (CMM_CD)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
