-- 입찰 시 구매자가 확정한 배송/직거래 방식을 낙찰 시점까지 보존한다.
ALTER TABLE BID
    ADD COLUMN BID_TRD_METHOD_CD VARCHAR(30) NULL COMMENT '입찰자가 선택한 거래방식공통코드(TRDG03)' AFTER BID_STATUS_CD;

-- 기존 단일 방식 입찰은 상품의 거래방식을 안전하게 이관할 수 있다.
UPDATE BID b
JOIN AUCTION a ON a.AUC_SN = b.AUC_SN
JOIN PRODUCT p ON p.PRD_SN = a.PRD_SN
SET b.BID_TRD_METHOD_CD = p.PRD_TRD_METHOD_CD
WHERE p.PRD_TRD_METHOD_CD IN ('TRDC0009', 'TRDC0010')
  AND b.BID_TRD_METHOD_CD IS NULL;

ALTER TABLE BID
    ADD KEY IDX_BID_TRADE_METHOD (BID_TRD_METHOD_CD),
    ADD CONSTRAINT FK_BID_TRD_METHOD_CD
        FOREIGN KEY (BID_TRD_METHOD_CD)
        REFERENCES CMM_CODE (CMM_CD)
        ON DELETE RESTRICT ON UPDATE RESTRICT;
