-- F-COM-018: ABUSE_REPORT에 신고 제목(ABR_TITLE_NM)·신고 대상 이름(ABR_TRG_NM) 컬럼 추가
ALTER TABLE ABUSE_REPORT
    ADD COLUMN ABR_TITLE_NM VARCHAR(100) NULL COMMENT '신고제목' AFTER ABR_REF_SN,
    ADD COLUMN ABR_TRG_NM   VARCHAR(200) NULL COMMENT '신고대상이름' AFTER ABR_TITLE_NM;
